"""Backfill a player's price history from real game logs.

Two steps, kept distinct on purpose (raw vs computed):
  1. Store each game as a raw ``PlayerGame`` observation (immutable source data).
  2. Reconstruct a point-in-time value series: at each game date, value the player
     from their season-to-date averages plus a rolling-form adjustment, and write
     a ``PriceBar`` stamped with the formula version.

Because raw games are stored separately, the whole price history can be
regenerated by any formula version — the model is auditable, not a black box.
"""

from __future__ import annotations

from datetime import timedelta
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.domain.player_value import (
    FORMULA_VERSION,
    PlayerStats,
    form_multiplier,
    production_score,
    shrink,
    value_index,
)
from app.models import Instrument, PlayerGame, PriceBar
from app.services.nba_espn import GameObs

FORM_WINDOW = 5


def _store_games(db: Session, instrument: Instrument, games: list[GameObs]) -> None:
    for g in games:
        existing = db.scalar(
            select(PlayerGame).where(
                PlayerGame.instrument_id == instrument.id,
                PlayerGame.espn_event_id == g.espn_event_id,
            )
        )
        row = existing or PlayerGame(
            instrument_id=instrument.id, espn_event_id=g.espn_event_id
        )
        row.game_date = g.game_date
        row.opponent = g.opponent
        row.home = g.home
        row.minutes = g.minutes
        row.points = g.points
        row.rebounds = g.rebounds
        row.assists = g.assists
        row.steals = g.steals
        row.blocks = g.blocks
        row.turnovers = g.turnovers
        if existing is None:
            db.add(row)


def _mean_stats(games: list[GameObs]) -> PlayerStats:
    n = len(games)
    if n == 0:
        return PlayerStats(0, 0, 0, 0, 0, 0, 0, 0)
    return PlayerStats(
        games=n,
        minutes=sum(g.minutes for g in games) / n,
        points=sum(g.points for g in games) / n,
        rebounds=sum(g.rebounds for g in games) / n,
        assists=sum(g.assists for g in games) / n,
        steals=sum(g.steals for g in games) / n,
        blocks=sum(g.blocks for g in games) / n,
        turnovers=sum(g.turnovers for g in games) / n,
    )


def _write_price(db: Session, instrument: Instrument, bar_date, value: float) -> None:
    existing = db.scalar(
        select(PriceBar).where(
            PriceBar.instrument_id == instrument.id,
            PriceBar.bar_date == bar_date,
            PriceBar.source == "nba_espn",
        )
    )
    bar = existing or PriceBar(
        instrument_id=instrument.id, bar_date=bar_date, source="nba_espn"
    )
    bar.close = Decimal(str(value))
    bar.currency = instrument.currency
    bar.formula_version = FORMULA_VERSION
    # Box score is available the day after the game (look-ahead safe).
    from datetime import datetime, timezone

    bar.as_of = datetime.combine(
        bar_date + timedelta(days=1), datetime.min.time(), tzinfo=timezone.utc
    )
    if existing is None:
        db.add(bar)
    # Session is autoflush=False; flush so a same-date lookup this run finds it
    # (updates in place) instead of inserting a duplicate.
    db.flush()


def backfill_player(db: Session, instrument: Instrument, games: list[GameObs]) -> int:
    """Store raw games and write the reconstructed price series. Returns bars written."""
    if not games:
        return 0
    # Dedupe by event id (ESPN can list a game under overlapping monthly buckets).
    seen: set[str] = set()
    games = [
        g for g in sorted(games, key=lambda g: g.game_date)
        if not (g.espn_event_id in seen or seen.add(g.espn_event_id))
    ]
    _store_games(db, instrument, games)

    # v2 prior (player quality). Falls back to the first observed value if a
    # player somehow has no stored prior, so shrinkage still runs.
    prior = float(instrument.prior_value) if instrument.prior_value is not None else None

    bars = 0
    for i in range(len(games)):
        season_to_date = games[: i + 1]
        recent = games[max(0, i + 1 - FORM_WINDOW) : i + 1]
        season_stats = _mean_stats(season_to_date)
        form = form_multiplier(
            production_score(_mean_stats(recent)), production_score(season_stats)
        )
        observed = value_index(season_stats, form_multiplier=form)
        p = prior if prior is not None else observed
        # G = games observed so far -> early season leans on the prior.
        value = shrink(observed, p, games=i + 1)
        _write_price(db, instrument, games[i].game_date, value)
        bars += 1

    # Emit a catalyst signal for the latest game (feeds the portfolio explainer).
    from app.services.catalysts import write_catalyst_signal

    write_catalyst_signal(db, instrument)

    db.commit()
    return bars
