"""initial schema

Revision ID: 4477bf743828
Revises: 
Create Date: 2026-08-30 01:41:08.238620
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base

revision: str = '4477bf743828'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('sport', sa.String(length=10), nullable=True),
    sa.Column('team', sa.String(length=60), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('external_ref', sa.String(length=40), nullable=True),
    sa.Column('headshot_url', sa.String(length=300), nullable=True),
    sa.Column('prior_value', sa.Float(), nullable=True),
    sa.Column('prior_basis', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player_games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('espn_event_id', sa.String(length=20), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.String(length=60), nullable=True),
    sa.Column('home', sa.Boolean(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('rebounds', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('steals', sa.Float(), nullable=False),
    sa.Column('blocks', sa.Float(), nullable=False),
    sa.Column('turnovers', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'espn_event_id', name='uq_player_game')
    )
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_games_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_games_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_bars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('close', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'bar_date', 'source', name='uq_price_bar')
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_bars_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=True),
    sa.Column('signal_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_ts'), ['ts'], unique=False)

    op.create_table('cash_balances',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', app.models.base.DecimalType(scale=4), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'currency')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', app.models.base.DecimalType(scale=8), nullable=False),
    sa.Column('price', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'idempotency_key', name='uq_orders_portfolio_idem')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('market_value', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('equity', app.models.base.DecimalType(scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_snapshot')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('positions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', app.models.base.DecimalType(scale=8), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'instrument_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('account', sa.String(length=60), nullable=False),
    sa.Column('cash_delta', app.models.base.DecimalType(scale=4), nullable=True),
    sa.Column('cash_currency', sa.String(length=3), nullable=True),
    sa.Column('quantity_delta', app.models.base.DecimalType(scale=8), nullable=True),
    sa.Column('instrument_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))

    op.drop_table('transactions')
    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))

    op.drop_table('orders')
    op.drop_table('cash_balances')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_ts'))
        batch_op.drop_index(batch_op.f('ix_signal_events_instrument_id'))

    op.drop_table('signal_events')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_bars_instrument_id'))

    op.drop_table('price_bars')
    op.drop_table('portfolios')
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_games_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_player_games_game_date'))

    op.drop_table('player_games')
    op.drop_table('users')
    op.drop_table('instruments')
    # ### end Alembic commands ###
